---
- name: Give ansible user sudo permissions
  become: true
  community.general.sudoers:
    name: 'ansible_superpowers'
    commands: "{{ l3d_users__ansible_user_command }}"
    nopassword: "{{ l3d_users__ansible_user_nopassword | bool }}"
    user: 'ansible'
    runas: "{{ l3d_users__ansible_user_runas | default('ALL')}}"
    state: "{{ l3d_users__ansible_user_state | ternary('present', 'absent') }}"
    validation: 'required'
