---
- name: Give admins superpower
  become: true
  community.general.sudoers:
    name: "{{ user.name }}-superpowers"
    user: "{{ user.name }}"
    state: 'present'
    commands: "{{ user.admin_commands | default('ALL') }}"
    runas: "{{ user.admin_runas | default(omit) }}"
    nopassword: "{{ user.admin_nopassword | default(false) }}"
  loop: "{{ _l3d_users__merged_users }}"
  loop_control:
    label: "user={{ user.name }}"
    loop_var: user
  when: user.state | default ('present') == 'present' and  user.admin | default(false) | bool

- name: Remove superpowers from Users
  become: true
  community.general.sudoers:
    name: "{{ user.name }}-superpowers"
    state: 'absent'
    user: "{{ user.name }}"
  loop: "{{ _l3d_users__merged_users }}"
  loop_control:
    label: "user={{ user.name }}"
    loop_var: user
  when: user.state | default ('present') == 'present' and not user.admin | default(false) | bool
