---
# create users
l3d_users__default_users: []
#  - name: 'alice'
#    state: 'present'
#    shell: '/bin/bash'
#    create_home: true
#    pubkeys: |
#       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPvvXN33GwkTF4ZOwPgF21Un4R2z9hWUuQt1qIfzQyhC
#       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAG65EdcM+JLv0gnzT9LcqVU47Pkw0SqiIg7XipXENi8
#       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJz7zEvUVgJJJsIgfG3izsqYcM22IaKz4jGVUbNRL2PX
#    exclusive_pubkeys: true
#    password: "$Password_hash"
#    admin: true
#    admin_commands: 'ALL'
#    admin_runas: 'ALL'
#    admin_nopassword: false
#    admin_ansible_login: true
#    groups: ['admin', 'foo', 'bar']
#  - name: 'bob'
#    state: 'present'
#    shell: '/bin/zsh'
#    admin: false
#    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"
#    exclusive_pubkeys: false

l3d_users__local_users: []
#  - name: 'charlie'
#    state: 'present'
#    admin: false
#    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"

# Create ansible mamagement user
l3d_users__create_ansible: true
l3d_users__ansible_user_state: 'present'
l3d_users__set_ansible_ssh_keys: false
l3d_users__ansible_ssh_keys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"
l3d_users__ansible_user_password: ''
l3d_users__set_root_ssh_keys: false
l3d_users__root_ssh_keys: ''
l3d_users__additional_groups: []

# run simple versionscheck
submodules_versioncheck: false
